project:
  type: website
  output-dir: _site
  render: 
    - README.md

site-url: "https://toledoem.github.io/StaticSiteImageOptimizer/"

website:
  title: "Static Site Image Optimizer"
  navbar:
    left:
      - text: "Repository"
        href: "https://github.com/ToledoEM/StaticSiteImageOptimizer"

format:
  html:
    theme:
      light: flatly   # Bootswatch theme (Bootstrap look)
    toc: true
    toc-location: left
    toc-depth: 4
    toc-expand: 2
    css: styles.css